/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/77jeP1AAy2b
 */
import { Card, CardTitle, CardHeader, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function Workspace() {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 lg:gap-6 bg-[#FDFBE6]">
      <div className="space-y-3">
        <Card className="rounded-xl overflow-hidden p-2 bg-[#FEEBC8] border-[#E6D5C1] border-solid border-2">
          <span className="w-full aspect-video rounded-md bg-gray-100 dark:bg-gray-800" />
        </Card>
        <Card className="rounded-xl overflow-hidden p-2 bg-[#FEEBC8] border-[#E6D5C1] border-solid border-2">
          <span className="w-full aspect-video rounded-md bg-gray-100 dark:bg-gray-800" />
        </Card>
      </div>
      <div className="space-y-3">
        <Card className="p-2 bg-[#FEEBC8] border-[#E6D5C1] border-solid border-2">
          <CardHeader>
            <CardTitle className="text-[#A2836E]">Video Settings</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-3 border-y py-3">
            <p className="text-sm/relaxed text-[#A2836E]">Adjust the video settings below:</p>
            <div className="space-y-1">
              <Label className="text-[#A2836E]" htmlFor="resolution">
                Resolution
              </Label>
              <Input
                className="bg-[#FDFBE6] text-[#A2836E] border-[#E6D5C1] border-solid border-2"
                defaultValue="1080p"
                id="resolution"
              />
            </div>
            <div className="space-y-1">
              <Label className="text-[#A2836E]" htmlFor="framerate">
                Frame Rate
              </Label>
              <Input
                className="bg-[#FDFBE6] text-[#A2836E] border-[#E6D5C1] border-solid border-2"
                defaultValue="60 FPS"
                id="framerate"
              />
            </div>
          </CardContent>
        </Card>
        <Card className="p-2 bg-[#FEEBC8] border-[#E6D5C1] border-solid border-2">
          <CardHeader>
            <CardTitle className="text-[#A2836E]">Audio Settings</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-3 border-y py-3">
            <p className="text-sm/relaxed text-[#A2836E]">Adjust the audio settings below:</p>
            <div className="space-y-1">
              <Label className="text-[#A2836E]" htmlFor="volume">
                Volume
              </Label>
              <Input
                className="bg-[#FDFBE6] text-[#A2836E] border-[#E6D5C1] border-solid border-2"
                defaultValue="80%"
                id="volume"
              />
            </div>
            <div className="space-y-1">
              <Label className="text-[#A2836E]" htmlFor="balance">
                Balance
              </Label>
              <Input
                className="bg-[#FDFBE6] text-[#A2836E] border-[#E6D5C1] border-solid border-2"
                defaultValue="Center"
                id="balance"
              />
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
